name: sample workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened]
      
  pull_request_review:
    types: [submitted]
      
      

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo 'first job is ready'
      

  
