name: sample workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened]
      
  pull_request_review:
    types: [submitted]
      
      

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
       - run: echo 'first job is ready'
       
  second-job:
    runs-on: windows-latest
    steps:
      - run: echo 'second job is ready'
      

  
